services:
  web:
    build: ./spa
    container_name: frontend-spa
    ports:
      - "3002:3000"
    # ToDo: upgrade docker compose so that we can use the watch feature
    # develop: 
    #   watch:
    #     - action: sync
    #       path: ./spa
    #       target: /spa
    #       ignore:
    #         - node_modules/

  backend:
    build: ./backend
    container_name: backend-service
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: db-service
    environment:
      MONGO_USER: user
      MONGO_PASSWORD: password
      MONGO_DB: mydatabase
    ports:
      - "5433:5432"